name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute on gradlew
        run: chmod +x gradlew

      - name: Validate wrapper
        uses: gradle/wrapper-validation-action@v2

      # Build en modo verboso y guardamos log a fichero
      - name: Build (verbose, save log)
        run: |
          ./gradlew clean assembleDebug \
            --stacktrace --info --no-daemon -Dorg.gradle.console=plain | tee gradle.log

      # Subimos el log SIEMPRE, incluso si falla el build
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-log
          path: gradle.log

      # Subimos el APK si existe (si no, solo avisa)
      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: warn
